Homework 5
eugene-okulik/andueleven pull request #4
Opened 2024-08-21 19:42 UTC by andueleven

Hello Eugeny! Could you please check my homework_5

2024-08-22 12:12 UTC, eugene-okulik requested changes

2024-08-22 12:12 UTC, eugene-okulik commented on homework/andrei_dubrouski/homework_5/test3.py
> +my_text = f'Students {sur1}, {sur2}, {sur3} study these subjects: {subj1}, {subj2}, {subj3}'
А здесь удобнее было бы возмользоваться `join`, а вдруг студентов или предметов станет больше или меньше.

2024-08-25 13:48 UTC, andueleven commented
Женя, добрый день!
Да, я разобрался с твоим комментарием - спасибо!
Перепроверь, пожалуйста, как будет возможность

2024-08-26 10:06 UTC, eugene-okulik approved these changes

2024-08-26 10:06 UTC, eugene-okulik commented on homework/andrei_dubrouski/homework_5/test3.py
> +text1 = str(', '.join(students))
В строку можно было не преобразовывать по двум причинам. 
1. join и так возвращает строку
2. когда мы используем f-string, все значения, которые мы вставляем в фигурных скобках сами преобразовываются в строку.

2024-08-26 10:06 UTC, merged